### ISSUE TITLE
Cannot Edit a Calendar Recurring Event

### ISSUE THREAD

**Issue by 995190** [etesync/etesync-web#102]
Something went wrong!

Material-UI: the `value` prop must be an array when using the `Select` component with `multiple`.

D</de<@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:1405035
N@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:967675
e@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:966906
e@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:967028
D@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:967370
z@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:968017
map@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:968186
D<@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:1404939
$i@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:1022444
xo@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:1028331
Po@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:1036918
Wa@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:1055713
Ya@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:1056095
Is@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:1062780
Ts@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:1062162
Rs@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:1068594
Tn@https://client.etesync.com/static/js/2.cf14224a.chunk.js:2:1001049

**Comment by AbleLincoln** [comment]
Fixed in #108

**Comment by tasn** [comment]
Ah sweet! Next time, please include "Fixes #108" in the commit message so that it automatically closes the ticket. :)
