### ISSUE TITLE
Add Support for Recurring Tasks

### ISSUE THREAD

**Issue by BeatLink** [etesync/etesync-web#107]
It would be great if etesync could support recurring tasks along with recurring calendar events. Its a part of the spec but so few clients implement it. And thats a shame because its such a useful feature.  If you guys implement this, i guarantee you it would put you on the map

**Comment by tasn** [comment]
CC @AbleLincoln who is working on improving the tasks.
As I told you on IRC it's supported by etesync-dav and Tasks.org. We plan on adding it for etesync-web too.

**Comment by AbleLincoln** [comment]
Absolutely, it's on my todo list! Will keep you updated @BeatLink. Should be ready in the next week or so.

**Comment by AbleLincoln** [comment]
Working on this now. Should adding a recurrence also affect the due date? For instance, if I add a recurrence rule for "daily", does that mean the due date is now today? And then after today, would it be updated to tomorrow? etc, etc for as long as the recurrence rule lasts

**Comment by BeatLink** [comment]
> Absolutely, it's on my todo list! Will keep you updated @BeatLink. Should be ready in the next week or so.

Awesome!

> Working on this now. Should adding a recurrence also affect the due date? For instance, if I add a recurrence rule for "daily", does that mean the due date is now today? And then after today, would it be updated to tomorrow? etc, etc for as long as the recurrence rule lasts

Well the way tasks.org does it is that it doesnt set a date until you actually complete it. Then it reschedules the next recurrence based on the completion date

**Comment by tasn** [comment]
> > Working on this now. Should adding a recurrence also affect the due date? For instance, if I add a recurrence rule for "daily", does that mean the due date is now today? And then after today, would it be updated to tomorrow? etc, etc for as long as the recurrence rule lasts
> 
> Well the way tasks.org does it is that it doesnt set a date until you actually complete it. Then it reschedules the next recurrence based on the completion date

Not quite. This is only the case if you enable `Repeat after completion`. Normally it just works like one would expect, it just repeats every week on the same time, which is the behaviour we should aim for @ablelincoln. Most repeating tasks happen at the same time on the same day (e.g. every Tuesday at 9am).

> Working on this now. Should adding a recurrence also affect the due date? For instance, if I add a recurrence rule for "daily", does that mean the due date is now today? And then after today, would it be updated to tomorrow? etc, etc for as long as the recurrence rule lasts

I would say yes, it should affect both. P.S, start date is the "hide until" field, and due date is the notification time field (and time to mark as overdue).

Take a look at how Tasks.org does things, it's a great app.

**Comment by AbleLincoln** [comment]
> > Well the way tasks.org does it is that it doesnt set a date until you actually complete it. Then it reschedules the next recurrence based on the completion date
> 
> Not quite. This is only the case if you enable `Repeat after completion`.

Actually I think @BeatLink is right here. I just did some investigating into Tasks.org (including looking at the resulting ical files). When you set a recurrence rule the app doesn't set a `Due Date` or a `Hide Until` or anything. If you don't set a `Due Date` manually, the app won't set one even if you have `Repeat after due date` selected (which is the default). Like @BeatLink said, if a task has a recurrence rule and no due date, the due date will be automatically added after the first time you complete the task. The due date is chosen by taking the recurrence rule from the moment you completed the task that first time.

For example, say I create a task and set it to `recur weekly`, `Repeat after due date`, but I _don't_ set a `Due Date`. Then maybe I wait a few days to actually check it off, say April 1. Then the due date will now be set to a week from April 1, so April 8. 

Of course none of this matters if you manually set a due date. Then it just works as expected. 

However, note that in Tasks.org a recurring task doesn't really "update" it's `Due Date` to the next recurrence after this one has passed.  Using my previous example, if I miss that April 8 due date, the task isn't automatically rescheduled for the following week (April 15). It won't be rescheduled _until_ I check it off (even if it is late).

This is just the way Tasks.org does it. We don't necessarily have to do it the same way, although I think their way makes sense.

**Comment by tasn** [comment]
> Actually I think @BeatLink is right here. I just did some investigating into Tasks.org (including looking at the resulting ical files). When you set a recurrence rule the app doesn't set a `Due Date` or a `Hide Until` or anything. If you don't set a `Due Date` manually, the app won't set one even if you have `Repeat after due date` selected (which is the default). Like @BeatLink said, if a task has a recurrence rule and no due date, the due date will be automatically added after the first time you complete the task. The due date is chosen by taking the recurrence rule from the moment you completed the task that first time.

OK, I haven't considered the no due date set scenario. We shouldn't support recurrence rule for that, because this is non-standard iCal. For a task to have an rrule, it *must* have DTSTART or DUE set.

> 
> For example, say I create a task and set it to `recur weekly`, `Repeat after due date`, but I _don't_ set a `Due Date`. Then maybe I wait a few days to actually check it off, say April 1. Then the due date will now be set to a week from April 1, so April 8.

I don't see the usecase, and the other etesync clients won't support it as it's not standard ical.

> 
> Of course none of this matters if you manually set a due date. Then it just works as expected.
> 
> However, note that in Tasks.org a recurring task doesn't really "update" it's `Due Date` to the next recurrence after this one has passed. Using my previous example, if I miss that April 8 due date, the task isn't automatically rescheduled for the following week (April 15). It won't be rescheduled _until_ I check it off (even if it is late).

If I got you correctly, that makes sense and is how it should work. Though it should reschedule it to the nearest *future* event, rather than the next event on the recurrence. So if you have a task that repeats monthly starting from the 1st of Jan. You ignore it until the 8th of May and then finish it. Now it should reschedule for the 1st of June, not 1st of Feb and not 8th of June.

> 
> This is just the way Tasks.org does it. We don't necessarily have to do it the same way, although I think their way makes sense.

I disagree. Let's not deviate from the standard unless we must.

**Comment by BeatLink** [comment]
Yeah, I think we should stick with the standard.

**Comment by AbleLincoln** [comment]
> We shouldn't support recurrence rule for that, because this is non-standard iCal. For a task to have an rrule, it must have DTSTART or DUE set.

Ah I had no idea. I think this a bug in Tasks.org then. They don't automatically set a `DTSTART` for recurring tasks.

In that case, should I automatically set a start time when someone selects recurrence? Or just error until they set one manually?

**Comment by BeatLink** [comment]
> In that case, should I automatically set a start time when someone selects recurrence? Or just error until they set one manually?

You can set a due date instead. Most people use that instead of star time. Start time is more of a "hide this task until" kinda thing

> Ah I had no idea. I think this a bug in Tasks.org then. They don't automatically set a DTSTART for recurring tasks.

Maybe you could open up an issue on their repo?

**Comment by AbleLincoln** [comment]
I agree that setting a due date makes more sense, but it looks like [according to the spec](https://icalendar.org/iCalendar-RFC-5545/3-8-2-4-date-time-start.html) a start date (`DTSTART`) is required.

**Comment by tasn** [comment]
The spec is a bit confusing on that one, but I'm 99% sure that dtstart is not required, so don't set that.

I would just error and mention that recurrence requires a due date or a start date.

**Comment by AbleLincoln** [comment]
Ok, and I assume the recurrence is calculated from whichever one of those (start or due) is specified?

**Comment by tasn** [comment]
Yeah, either or both. Just consider them as two separate fields that separately have recurrence applied to do that advances in tandem.

**Comment by BeatLink** [comment]
Well I'm not sure about the spec but what I did in my todo app was, if either the start or due date was set, I'd calculate the recurrence based on that, but if *both* were set, then I'd save the difference between the start date and due date (say start date is 3 days and 12 hours before due date), update the due date using the recurrence, and then setting the start date to the same difference previously (say start date being 3 days 12 hours before).

**Comment by tasn** [comment]
You can't really do that in iCal though for all I know, unless you just edit the event manually every time and change the start date yourself...

**Comment by AbleLincoln** [comment]
So _shouldn't_ edit the event manually upon completion? This is what Tasks.org does, but I wasn't sure if this is proper use of the ical standard.

**Comment by AbleLincoln** [comment]
Like I'm not sure if the due date/start date are supposed to be calculated from the recurrence rule every time I load the task, or if I update the due date/start date on the ical object anytime it's necessary (i.e. upon completion).

**Comment by tasn** [comment]
To be honest, I have no idea, so I asked the developers of Evolution, the GNOME email (and PIM) client, and what they do makes a lot of sense, in addition to being the same as what Exchange does (according to them).
Essentially, what they do, is expand tasks upon completion. What does that mean? It means they mark the original as completed, and then create a new recurring task with the start date of the next recurrence instance and everything else the same (except that if the rrule has a count limit, decrease it by 1).
This fixes my concerns about editing tasks removing past information about when the task was originally created, and when it was actually completed in the past.

For reference, here's the code from Evolution (you don't actually need to read it):
https://gitlab.gnome.org/GNOME/evolution-data-server/-/blob/master/src/calendar/libecal/e-cal-util.c#L2361
https://gitlab.gnome.org/GNOME/evolution-data-server/-/blob/master/src/calendar/libecal/e-cal-util.c#L2425

Please note, that they require having dtstart for recurring events, though they too are not entirely sure what the standard mandates, so let's not make it a requirement for now. It's easy to just make it one in the future.

Let me know if you have any other questions.

**Comment by AbleLincoln** [comment]
Haha I love how no one is really sure how to interpret the standard. Isn't the whole point of a standard to, well, _standardize_ things?

Regardless, what GNOME does makes sense. I'll go ahead and implement it that way.

**Comment by AbleLincoln** [comment]
Question: does a cancelled task cancel just this instance of the recurrence or all following instances?

**Comment by tasn** [comment]
Do we have a concept of cancelled? What does it do everywhere else? I'd say no though, if you want to delete all instances, you need to delete the task. And when you do that, it only deletes the current iteration, not the past ones that have already been completed.
This is just me making things up as I go, not sure if this is the best way to go at it, or just a way. :)

**Comment by AbleLincoln** [comment]
> if you want to delete all instances, you need to delete the task. And when you do that, it only deletes the current iteration, not the past ones that have already been completed.

This makes sense. I looked at Tasks.org for reference but they don't even allow you to cancel events. It's just Needs Action, Completed, or simply deleted.

**Comment by AbleLincoln** [comment]
I have another issue. The deeper I dig into this the more edge cases I find lol.

So I am using ical.js' rrule [iterator](http://mozilla-comm.github.io/ical.js/api/ICAL.Recur.html#iterator) to find the next event in the series. Like we discussed above, rescheduling a task should always go to the nearest _future_ task (so basically skipping over any recurrences we may have missed). However a problem arises when limiting recurrences by number. Say we schedule a task on April 1 to recur daily for only 5 repeats. If you wait until April 6 to complete the first instance, the iterator will fail to find any future recurrences of the task (because it will run out of repeats before April 7).

How should I handle this? Is this intended behavior? Is the recur limit supposed to count missed days?

**Comment by tasn** [comment]
Oh god, indeed sounds like an annoying edge case! I think most people won't even hit it though, as in, I think they'll just finish the task before the next iteration. I think that if someone sets a task to recur 5 times, then it should recur 5 times, even if the 5th time is a year after what it was meant to be when the task was initially created...
What do you think?

As for for the multiple states of tasks, the allowed ones in ical are in-progress, needs action, completed and cancelled if memory serves. I don't mind it if you map in-progress and needs action to the same thing (not done). Mapping completed and cancelled to the same thing (done) could be fine too, though I personally like having the concept of cancelling a task. Though I really don't feel strongly one way or the other.
