### ISSUE TITLE
Provide static files for self-hosting

### ISSUE THREAD

**Issue by rugk** [etesync/etesync-web#11]
Is not this in the end only a static site with a lot of static files CSS and stuff? (Otherwise PGP signing would not work, so I assume yes.)

In this case, please do publish ZIPs for each release containing all the files statically build, so no one needs to have the hassle of running yarn or such stuff and can just download the files and place them on their server. 
Make self-hosting (and thus likely also contributing) easy!

**Comment by tasn** [comment]
It is just a static site, and this is a very good point. Will hopefully get around to doing it tomorrow, and every release from now on.

**Comment by tasn** [comment]
Done (see the release page).
