### ISSUE TITLE
Allow self-hosting in subdirectories/use relative links

### ISSUE THREAD

**Issue by rugk** [etesync/etesync-web#13]
Currently you use absolute links such as `/static/css/main.67044f6b.css` and `/static/js/main.135a159b.js`.

That is not nice, as it prevents to self-host the instance in a subdirectory, e.g. `domain.example/mysubdir`, as the browser then always tries to load the resources from the root of the web server.

Judging from ZIP file. Maybe you can fix that by setting `%PUBLIC_URL%` to `.` so the URLs point to `./…`.

**Comment by tasn** [comment]
Hey,

Thanks for opening this. This is supported, you just need to configure your web server accordingly. It's a bit of a pain in the ass with django I guess, but anyhow:

https://stackoverflow.com/questions/8133063/how-to-deploy-django-under-a-suburl-behind-nginx

**Comment by rugk** [comment]
Sorry, no. I am talking about three static zip file!
I certainly do not want to run yet another web sever just for some static files in production (and you hopefully also don't), so setting any header won't help.

Can't you just set the variable to `.` when building the zip?

(In any case, please reopen, this issue is not solved.)

**Comment by tasn** [comment]
So sorry, my fault! I didn't see it was the web one...
You can't do ".", it has to be an absolute URI because:
"/", "/pim/" and etc all point to index.html and all need to work with these files, and the files are not in the "pim" directory, so any non root would fail (when you refresh the page).

I suggest that if you're running it locally just run "python -m http.server SOME_PORT", and access it this way. If you are using a proper server, just create a different domain. You can modify /etc/hosts and have whatever domain you want there. So for example "etesync" could lead to it.

I'd recommend (and personally use) the python -m approach.

I was about to reopen it, but actually, I don't see a way to fix it.

With that being said, it's fairly trivial to change the paths of the resource files. You only need to change index.html.

How are you serving these files? What server?

**Comment by rugk** [comment]
Hmm, ok, so `/pim/` wants to reuse these files? For what is `/pim` even used, BTW? Maybe one can just not use this?

And in the self-hosted version with ZIP accessing `/pim` won't work anyway, as such a dir does not exis. So taht pim thing, seems optional.

nginx, BTW, and I still want a solution with static files. You only have 4 files or so. It is not so hard t6o make the paths relative then. And if there is another subdir using the files, it has to use `..`.

**Comment by tasn** [comment]
This is the nginx directive you should be using:
```
 location / {                                      
      try_files $uri $uri/ /index.html =404;       
 }                                                 
```

As you can see, it just tries files, and then just shows index.html if the file doesn't exist. So /pim/ will also show index.html. The reason for that is that etesync-web uses the browser history when you navigate between page. This works locally, so it's not a problem, but upon refresh, it'd still request index.html. This wouldn't work with the "python -m" solution btw, you'd need a local nginx.

It's common practice with web apps. And is the default with react-router.

I can't use "." and "..", because it's all the same file index.html.

**Comment by rugk** [comment]
You still did not say what `/pim` is actually used for.

I am hosting it under `/subdir`. Reasons hardly matter, but for this thing, you may e.g. prevent it from being found by search engines or so if you do not want. (and robots exclusions or such stuff are ugly.)
And it seems I do not need `/pim`when using the application. So when PIM is really needed, you can just create a new index.html with `/subdir/pim`. This latter index.html can then (thanks to relative URLs) also used for `/subdir/whatever` etc…
So this also has it's advantage, you just need one index.html more.

> It's common practice with web apps. And is the default with react-router.

Then it is bad practice. By having relative URLs you could also host multiple (test) versions of the same web app, etc.

**Comment by rugk** [comment]
You still did not say what `/pim` is actually used for.

I am hosting it under `/subdir`. Reasons hardly matter, but for this thing, you may e.g. prevent it from being found by search engines or so if you do not want. (and robots exclusions or such stuff are ugly.)
And it seems I do not need `/pim`when using the application. So when PIM is really needed, you can just create a new index.html with `/subdir/pim`. This latter index.html can then (thanks to relative URLs) also used for `/subdir/whatever` etc…
So this also has it's advantage, you just need one index.html more.

> It's common practice with web apps. And is the default with react-router.

Then it is bad practice. By having relative URLs you could also host multiple (test) versions of the same web app, etc.

**Comment by tasn** [comment]
Try using it, and you'll see the addresses changes dynamically. It's not just /pim, it's also /pim/contacts/SOME-UID. I can't create directories, there are infinite possibilities.

It doesn't matter for usage, it matters when a user refreshes.

It's not bad practice, it's the only way to do it. You have a web app, which is an HTML file and some JS. It has navigation inside (so the apps accept different urls), so it needs to be served from multiple urls.

You can build your own version which uses a subdirectory, but that means you can't use the statically built one. You could also make nginx just try also serving from your directory, so for example:
```
 location /static {                                      
      try_files $uri YOUR_SUBDIR_NAME/$uri =404;       
 }   
```

There are really a lot of ways to do it. It just can't be done without correctly configuring your web server.

I think you need to try using it, looking at the address bar, and then refreshing. You'll see what I'm talking about.

**Comment by rugk** [comment]
Ah I see now.

IMHO it would be better if you change the URL to actually not "fake" the server structure, because then self-hosting a static ZIP file is anyway not going to work if the user refreshes.
So better do the URL like this:
```
domain.example/anysubdirifneeded/#/pim/contacts
```

The `#` is the usual indicator for all "only in browser" stuff. It has other advantages:
* I am not sure, but I thought some browsers are actualyl triggering a reload when you change the main `/` part of the domain. So you could not even uise it without manually reloading.
* It avoids metadata. Everything after the `#` is not sent to the server. (even in case of a manual reload.
* It still looks the same. Nobody notices this character.

So maybe let's open a new issue for that? Or just handle it here?

And I understand why it's best practice for others, they basically have an `index.php/…`, which handles all requests, so they can do that but here you want a static bundle, so that is not really nice.

Better best practises for you here were e.g. Mega.nz or [Threema Web](https://github.com/threema-ch/threema-web) or so… There they do it by just changing the `#`.

**Comment by tasn** [comment]
I'm familiar with #, and EteSync web used that in the beginning, unfortunately it created some issues. See https://reacttraining.com/react-router/web/api/HashRouter for more information.

Excerpt:

> IMPORTANT NOTE: Hash history does not support location.key or location.state. In previous versions we attempted to shim the behavior but there were edge-cases we couldn’t solve. Any code or plugin that needs this behavior won’t work. As this technique is only intended to support legacy browsers, we encourage you to configure your server to work with <BrowserHistory> instead.

So unfortunately it's not possible. :(

**Comment by rugk** [comment]
Hmm, but do you need this location.key and location.state for that? Don't exactly what it refers to, but basically you only need to get the current URL and modify it, is not it that?

**Comment by tasn** [comment]
I use location.state in EventEdit.tsx

**Comment by royalhacker** [comment]
"homepage": ".",

**Comment by rugk** [comment]
@royalhacker What do you want to express by that?

**Comment by royalhacker** [comment]
@rugk add this option in package.json to make the path relative to directory in which you host the build files.

**Comment by tasn** [comment]
Thanks @royalhacker  \o/

I wonder if it's better to just have people explicitly set their path, such as: `"homepage": "/etesync"`, rather than the relative directive. See https://github.com/facebook/create-react-app/issues/1487#issuecomment-277727669

**Comment by royalhacker** [comment]
👍

**Comment by rugk** [comment]
> I wonder if it's better to just have people explicitly set their path, such as: `"homepage": "/etesync"`, rather than the relative directive.

Maybe this can be documented in this repo/wiki somewhere? Otherwise this very useful info/solution can get lost.

**Comment by tasn** [comment]
Are you able to test it and verify it works? If you are, I'm happy to add it to the README.

**Comment by royalhacker** [comment]
yes. it works. you can add it to the README.
