### ISSUE TITLE
Adding tags in tasks

### ISSUE THREAD

**Issue by natenjo** [etesync/etesync-web#133]
Hi,
I think etesync-web is missing a functionality to add tags.  When creating a new task and I specify a non existent task, it won't be created.  The autocomplete also just suggests the predefined "work" and "home" tag to me.

Would be cool if this could be fixed/created.

Thanks
Jonathan

**Comment by tasn** [comment]
Yeah, it's a known issue. @AbleLincoln is working on it, andI have an idea on how to add it very easily, so hopefully it'll be available very soon.

**Comment by tasn** [comment]
@natenjo: I just fixed this. The autocomplete is still bad, but at least you can add whatever tags you want. :)

**Comment by tasn** [comment]
I'm going to close this ticket because fixing the autocomplete is a different issue and is already known. Please reopen if I missed anything.
