### ISSUE TITLE
Parse Errors found "Error: Failed to fetch"

### ISSUE THREAD

**Issue by n8rade** [etesync/etesync-web#140]
Seeing 99+ Parse Errors according to the icon in the latest build. They all appear to be the same.

Error: Failed to fetch
    at t [as constructor] (https://calendar.local/static/js/2.87921627.chunk.js:2:3635)
    at new t (https://calendar.local/static/js/2.87921627.chunk.js:2:3887)
    at https://calendar.local/static/js/2.87921627.chunk.js:2:10412

![image](https://user-images.githubusercontent.com/65125624/86916622-7faa4680-c0e9-11ea-97fe-f068cfc928c1.png)

**Comment by tasn** [comment]
Hey,

Have you built your own etesync-web, or did you just use the prebuilt tar.gz? Just wondering how to investigate further. If you built it yourself, could you maybe try again with a debug build (just run it locally by running `yarn start`).
Btw, could check the network tab in the browser's developers console to see if there are any networking errors? I suspect that may be it, though not sure.

Thanks!

**Comment by n8rade** [comment]
Hello,

I made a script that updates the web client with the latest pre-built tar.gz from the static link nightly.

Otherwise, it appears that you were completely correct!

![image](https://user-images.githubusercontent.com/65125624/87043716-1bf04e00-c1bb-11ea-807a-5bbb0967396f.png)

I used a self-sign cert, but this is the first time that I recall seeing the error since I set it up.

**Comment by tasn** [comment]
Self-signed certs aren't blocked, though I guess you need to tell the browser to trust them. Could you open https://calendar.local/admin/ and make sure you can view the page without an error? If there's an error, tell FF to remember this cert?

As for the changes, there are have been a few changes that could be related, though to be honest, they all look like they would uncover issues rather than cause them.

Try the above with the accepting the cert and report back please.

**Comment by n8rade** [comment]
When you say https://calendar.local/admin/, do you mean the admin page for the django server? That's at https://calendar.local:8000/admin/ for me. I actually did go into that and log in with my user because I was not able to log into the web page and thought I might be forgetting what my login details were. My browser did warn for a self signed cert and I did accept the cert in my browser, but that did not seem to change the behavior of the Web UI after going back to try to log in again and confirming I had the right info for my credentials.

I will try doing some more testing tonight with the non-working build and report back.

**Comment by n8rade** [comment]
So this is strange.

I switched back to the "broken" build that was throwing errors for me and I was able to log in again. I'm seeing these messages in developer tools now:

![image](https://user-images.githubusercontent.com/65125624/87188389-5be72c00-c2b4-11ea-9a1f-0ef91d97aa1f.png)

But everything appears to be working fine now. I will update if the parse errors/certificate errors come back.

**Comment by n8rade** [comment]
So, I just found that the parse errors returned.

![image](https://user-images.githubusercontent.com/65125624/87234866-c5da0100-c39a-11ea-9abc-2eaa73a80ffe.png)

After running into this, I logged out and went to calendar.local:8000/admin and accepted the proceeded through the warning about the self-signed certificate. I was already logged in, so I went back to the web UI and entered my log in information and I was in.

Opening a different browser and going directly to the web UI I received "Error! NetworkError when attempting to fetch resource." upon trying to login.

![image](https://user-images.githubusercontent.com/65125624/87235206-66cabb00-c39f-11ea-9763-b70ff6749862.png)

I then went to the django admin interface and accepted the security risk and logged in there just fine. I refresh the web UI page again and I can log in. I'm not sure what was causing the original login errors on the first time running into this, but it appears that I can at least workaround any login issues now.

Thank you!

**Comment by tasn** [comment]
So does everything work now? It's not an issue with the web client, but rather just how browser security works. If you have an untrusted SSL certificate, requests to that server will fail. Nothing we can do about it.

I'm closing this ticket with the assumption it's fixed. If it isn't, please reopen it.

**Comment by gdahia** [comment]
Greetings. I am experiencing 15 errors similar to this one, and I am using the paid hosting option for `etesync`.

The message is:
```
t@https://client.etesync.com/static/js/2.654df5fa.chunk.js:2:3635
t@https://client.etesync.com/static/js/2.654df5fa.chunk.js:2:3887
T</e.prototype.newCall/</<@https://client.etesync.com/static/js/2.654df5fa.chunk.js:2:10412
```

![Screenshot from 2020-07-13 19-25-28](https://user-images.githubusercontent.com/13017652/87359831-14280500-c53f-11ea-84f9-f67c105cb329.png)

**Comment by tasn** [comment]
Are you able to access www.etesync.com? Does it still happen to you? This error just looks like a momentary network issue (which me most definitely need to show nicer error messages for{.

**Comment by gdahia** [comment]
> Are you able to access www.etesync.com?

Yes, I am.

> Does it still happen to you?

It didn't happen again, but I didn't use the web client much these past few days.

I will keep an eye to see if it happens again. Thanks for the clarification.

**Comment by tasn** [comment]
Please do. Thanks!
