### ISSUE TITLE
no subtasks?

### ISSUE THREAD

**Issue by SchnozGuy** [etesync/etesync-web#144]
only support for checklists but no support for subtasks?

i would be very disappointed if it is true, as im using [Tasks.org Android app](https://play.google.com/store/apps/details?id=org.tasks) which is very neatly designed and customizable. unfortunately when i go EteSync website all the subtasks show as separate tasks.

**Comment by tasn** [comment]
Oh, so they do show, but show as separate tasks! I misunderstood that from your other report. I'll take a look at implementing it.

I'm closing this ticket in favour of #124 which already covers the same issue. Please subscribe there for notifications.

I'm sorry for suggesting you open a ticket, I didn't realise the tasks show for you, I thought you said they didn't.
