### ISSUE TITLE
recurring events in calendar not being synced properly

### ISSUE THREAD

**Issue by awefartib** [etesync/etesync-web#15]
Recurring calendar events added on Android do not show up on etesync-web. Only the first date of each event seems to get synced to etesync-web.

It would also be great if recurring events could be added directly from etesync-web.

**Comment by tasn** [comment]
Thanks for reporting. This is indeed not yet implemented. Not the view side nor the edit side.

**Comment by dan-v** [comment]
@tasn - how much work do you think is required to implement this feature? 

Even having just the backend support would make the calendar experience a lot more seamless when syncing from desktop or phone. Right now, I need to either manually add re-occurring events by hand as individual events or add a re-occurring event on both desktop and phone and live with the fact it won't be synced in etesync properly.

**Comment by tasn** [comment]
Probably not that much work to be honest. Just need to do it. The recurrence rule is properly synced, it's just a matter of plugging it to the UI... Maybe I can take a jab at it this weekend.

**Comment by tasn** [comment]
Took me forever, and I'm so sorry for that, though it's here now! :tada: 

It's not fully supported just yet, but at least the events now show. :) Please take a look at the commit message for more info.

**Comment by dan-v** [comment]
Thanks @tasn! 🎉🎉
