### ISSUE TITLE
Feature Request: tasks Tags Overhaul

### ISSUE THREAD

**Issue by Pleasantless** [etesync/etesync-web#152]
- suggest already-used tags
currently, when typing in the tags field you only get the 2 suggestions "Home" and "Work" even if you do not use such tags. it would be more useful if the dropdown suggestions showed tags that exist in the lefthand pane.

- remove case sensitivity
tags are case sensitive which makes typing your own tags sometimes annoying, as they get added to a new tag category if you do not use correct upper/lower forms.

- auto tag
when selecting a tag such as "exercise" from the leftpane,  then selecting to add a tag, it would be neat to have the task automatically tagged as "exercise".

- include subtasks  
when viewing a specific tag, if the main task has subtasks they are hidden unless also tagged. it would be more practical to have them visible

**Comment by tasn** [comment]
Thanks for all the great ideas! I already started looking at it as part of the overhaul of the web client that I'm planning very soon. I hope to incorporate all of these then.

**Comment by tasn** [comment]
I just fixed the first point. The second and fourth shouldn't be too hard either though unfortunately I won't get to them in the next couple of weeks because I'm overhauling this code anyway, so better to fix it after the overhaul.

**Comment by SchnozGuy** [comment]
I never saw any program get updated as this, sothis means one fo the following:
_ youre very talentd at coding
_ you work hard
_ this is very easy
thank you anyway. it is neat and imm impatiently waiting for the overhaul.

**Comment by tasn** [comment]
Haha, thanks. :)

Overhaul: me too. I already have most of it ready, it's just waiting on related changes. I'm hoping to write a blog post about it soon.
