### ISSUE TITLE
ERROR on clicking subtask

### ISSUE THREAD

**Issue by mnotforme** [etesync/etesync-web#158]
I get ![this error](https://user-images.githubusercontent.com/69506895/90320013-03a3e980-df46-11ea-95f5-c4c35f248ab6.png)
 whenever I click on a specific reocurring subtask. Im using Chromium: 84.0.4147.125 (Official Build) (64-bit)

**Comment by tasn** [comment]
Could you please copy and paste the text of the error here? It'll help with figuring out where it failed.
As for the issue, you said it's just happening for a specific task, or for many tasks? Do other subtasks work?

**Comment by mnotforme** [comment]
Minified Material-UI error #2; visit https://material-ui.com/production-error/?code=2 for the full message.
Error: Minified Material-UI error #2; visit https://material-ui.com/production-error/?code=2 for the full message.
    at https://client.etesync.com/static/js/2.86a088d7.chunk.js:2:1580205
    at Array.map (<anonymous>)
    at https://client.etesync.com/static/js/2.86a088d7.chunk.js:2:1580113
    at Ko (https://client.etesync.com/static/js/2.86a088d7.chunk.js:2:1178640)
    at Ia (https://client.etesync.com/static/js/2.86a088d7.chunk.js:2:1186638)
    at vs (https://client.etesync.com/static/js/2.86a088d7.chunk.js:2:1227311)
    at uc (https://client.etesync.com/static/js/2.86a088d7.chunk.js:2:1217579)
    at sc (https://client.etesync.com/static/js/2.86a088d7.chunk.js:2:1217504)
    at Js (https://client.etesync.com/static/js/2.86a088d7.chunk.js:2:1214513)
    at https://client.etesync.com/static/js/2.86a088d7.chunk.js:2:1165898

just 1 specific subtask.

**Comment by tasn** [comment]
Doesn't add much useful information unfortunately. :|
What we can do though: could you please send me a censored version of the task? The way to do it is to go to the side menu (top left corner) -> Journals -> Click on the task list -> find this task in the list and click on it.
It'll now show you the raw representation of the task, if you could copy and paste it here, that would be great! Obviously feel free to replace the "summary" content and other sensitive information with XXXXXXXX

**Comment by tasn** [comment]
I just pushed a fix. I believe I fixed everything, but in case it hasn't, let me know. There could be some lingering issues there that I've missed.

**Comment by mnotforme** [comment]
i apologize for the late reply. your fix has... fixed it all. Good work.

**Comment by tasn** [comment]
That is not late, it took you an hour. :P
Anyhow, thanks a lot and great to hear!
