### ISSUE TITLE
EteSync 2.0 Migration Tool: Non descriptive error message when username is already used

### ISSUE THREAD

**Issue by cniesen** [etesync/etesync-web#163]
My initial conversion from 1.0 to 2.0 failed with an HTML field validation error or something like it (forgot to write it down).  In any case it wasn't very clear what happened. After a few tries I figured out what the issue was.

My 2.0 user name was the same as my 1.0 user name (i.e. the email address).  It was auto populated thanks to my browser and I never though anything about this.  Using a new username worked fine.

I'd suggest to display "Username already used", "Username not available" or at least "Invalid username".

**Comment by tasn** [comment]
Thanks for the report, I believe it's now been fixed!
