### ISSUE TITLE
[Feature] Import .ics files

### ISSUE THREAD

**Issue by Nuntius0** [etesync/etesync-web#17]
Occasionally, e.g. when booking tickets for flights, concerts, etc, they email you an `.ics` file with all the calendar info ready at hand. 
I envision a button at the bottom of the manual input view reading `Import *.ics`.

**Comment by tasn** [comment]
This is a fantastic idea!
I'll take a look into adding it soon, shouldn't be too hard. Just need to figure out exactly where it should be. Maybe a new import tab. The reason for that is that if I'm going to do it, I may as well support importing ICS and vCards with many contacts/events.

If it was only one, I could just do it in the new event/new contact pages and then let you edit them directly, but with multiple it's better to have a different page.
