### ISSUE TITLE
Recurring tasks are hidden

### ISSUE THREAD

**Issue by shompoe** [etesync/etesync-web#172]
Create a task in tasks.org. Set a due date any time in the future (tomorrow) and make it recurring (every day). Sync up and look for the task on the web client. You will have to enable hidden tasks to find it. Open it and look at the details. Hide untill will be set to the same value as the due date. Delete the value from hide until, save, and go back in. It will not have saved the change.

**Comment by tasn** [comment]
`Hide until` is unfortunately not currently synced from Tasks.org. It's a limitation with Tasks.org, not with EteSync. Take a look at https://github.com/tasks/tasks/issues/984 and related tickets for discussions.

**Comment by shompoe** [comment]
Yes, but the task is not hidden in tasks.org. Etesync is hiding recurring tasks that are not/should not be hidden. If you modify the task in tasks.org so that it does not recur then etesync no longer hides it.
--- 
Mark Desrousseaux



18 Oct 2020, 08:04 by notifications@github.com:

**Comment by tasn** [comment]
Could you show me the RAW versions (from the etesync changelog) of a task that should show but is hidden? I still believe it is what I said. That Tasks.org just doesn't sync the start date so even when you remove hide until in tasks.org it's not being synced.

**Comment by shompoe** [comment]
OK

So since solving the sync. issues on my phone I just moved all my tasks to tasks.org internal list, deleted and recreated etesync list, and transferred them all back to etesync. Now when I log in from web client none of my tasks are being hidden.

Who would have thought???



--- 
Mark Desrousseaux



18 Oct 2020, 17:05 by notifications@github.com:

**Comment by tasn** [comment]
It sounds like it's not syncing. How about creating a task manually, does that sync it?

**Comment by shompoe** [comment]
OK, no problem any more.       Wiped everything and started from fresh.     And tasks are no longer getting hidden.

**Comment by tasn** [comment]
Great. :)
