### ISSUE TITLE
Tasks sometimes not staying deleted

### ISSUE THREAD

**Issue by shompoe** [etesync/etesync-web#173]
Sometimes when I delete tasks from tasks.org, I will never again be able to find them in tasks.org (kind of the point) but they still persist in the web client.

Just now I was able to track down two test tasks that exhibited this behaviour in the journal. Immediately after task creation event is the task deletion event, and then right after that is a task edit event, in the journal. So as far as Etesync is concerned these tasks still exist. But they are not syncing back down to tasks.org

**Comment by tasn** [comment]
Sounds like a bug with either Tasks.org or the EteSync Android client. Could you please repost it in https://github.com/etesync/android/ ?
How are you using Tasks.org? Did you put your etesync credentials directly into Tasks.org, or does it automatically sync with EteSync using the EteSync Android app?

Closing this in favour of the ticket in the android repo.
