### ISSUE TITLE
EteSync2 Web: No Account

### ISSUE THREAD

**Issue by Pleasantless** [etesync/etesync-web#177]
whenever I try to sign in with my original EteSync app, Iit tells me I have no account. what is up?

**Comment by tasn** [comment]
The EteSync 1.0 web app is at https://client.etesync.com use that if you haven't updated your account.
For the 2.0 account, use the new address and your username.

I'm closing this ticket as I think it's resolved, but plesae let me know if it's not the case.

**Comment by Pleasantless** [comment]
how do i update it?

**Comment by tasn** [comment]
https://blog.etesync.com/etesync-2-0-is-now-released/

**Comment by Pleasantless** [comment]
it has been many minutes since i started the migration process via Android app, and "Setting up Encryption" has been loading for over 10 minutes...
