### ISSUE TITLE
Creating a task with the webapp create an empty tag

### ISSUE THREAD

**Issue by sdeleuze** [etesync/etesync-web#179]
After creating a new task with just a title, when I edit it I see an empty tag.
![image](https://user-images.githubusercontent.com/141109/98448367-c9ed1400-212b-11eb-82aa-440c82f57d0b.png)
Tasks created by the iOS app do not have the same issue.

**Comment by tasn** [comment]
Oops! Weird that I haven't noticed it myself. Maybe it's a new regression.
