### ISSUE TITLE
Don't you need to ask users to accept terms and conditions?

### ISSUE THREAD

**Issue by Nautman** [etesync/etesync-web#188]
Currently [the terms of service (TOS)](https://www.etesync.com/tos/) isn't mentioned anywhere when creating an account. Whether it's actually required by law or not (which I think it might be), I think it's reasonable to mention it anyway.

If you were to implement it clearly I also suggest that you add a simple way of downloading the terms that a user has agreed to, as it should be best practice to give users a copy of every contract they enter.

I like your project and am looking forward to see how it develops!

**Comment by tasn** [comment]
Thanks for the report! It's a stupid oversight we made when moving to the app-based signups (we used to have a web-page). I'll try to get to it today, if not, please chase me, as it's really important! Sorry. :(

**Comment by Nautman** [comment]
No worries, I just thought I'd let you know! :)

**Comment by Nautman** [comment]
Hey! Do you know if it is difficult to implement this? :)

**Comment by constantinosgeorgiou** [comment]
I would like to help implement this. What is needed?

**Comment by tasn** [comment]
Sorry, I just fixed it! It's very easy to implement but I was just swamped with other things and kept on forgetting about it. :(

**Comment by Nautman** [comment]
No worries, good job! :)
