### ISSUE TITLE
Little UX Improvement for new events

### ISSUE THREAD

**Issue by SeanPedersen** [etesync/etesync-web#195]
Hey great project, using it for a while now.
I have a small but IMO useful suggestion for the UX: When creating a new event that is not all day (instead with a fixed start and end point), the current UX forces me to set both a start and an end time. It would be convenient if after I set the start time, if etesync-web could automatically set the end time to the start time + half an hour. This would allow me to save time if I only care about the start time.

Anyway hope you get what I am saying. Available for further questions.

**Comment by SeanPedersen** [comment]
Damn that was fast, THANKS A LOT!

**Comment by tasn** [comment]
Was an easy fix and a big issue. Thanks for reporting!
