### ISSUE TITLE
Login not working after upgrade

### ISSUE THREAD

**Issue by SeanPedersen** [etesync/etesync-web#196]
Just upgraded both server and web to latest versions. When I try to login (set my server URL) I get following error:
`undefined is not iterable (cannot read property Symbol(Symbol.iterator))`

**Comment by tasn** [comment]
Can you check the network tab in the browser's developer tools? Any errors there? Are you using https://pim.etesync.com? Or https://client.etesync.com?

**Comment by SeanPedersen** [comment]
I am self hosting at: https://eteweb.neotree.uber.space/login
Server: https://ete.neotree.uber.space/login

Network tab does not record any request on Login Button press. So probably client side error: 
```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at e.exports (createForOfIteratorHelper.js:4)
    at Function.urlExtend (Etebase.js:2)
    at Etebase.js:2
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at n (asyncToGenerator.js:3)
    at A (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
```

**Comment by tasn** [comment]
Do you get the same issue with https://pim.etesync.com ? Feel free to just use a bad password as we are checking if it fails before the password verification anyway...

**Comment by SeanPedersen** [comment]
There everything works as expected: `User not found`

**Comment by SeanPedersen** [comment]
So sth wrong with my client...

**Comment by tasn** [comment]
Yup... I don't know what it could be, but maybe you have old versions of some things that are buggy. Hard to guess. :|

**Comment by tasn** [comment]
What happens if you download the prebuilt client at https://pim.etesync.com/etesync-web.tgz and try to self-host it, does that work? Or still fail?

**Comment by SeanPedersen** [comment]
Hey that is working! But it's missing your latest awesome feature (I requested) :D ...

**Comment by SeanPedersen** [comment]
I might try reinstalling eteweb completely

**Comment by tasn** [comment]
Weird, it should include the latest awesome feature! Let me know how reinstalling goes for you.

**Comment by SeanPedersen** [comment]
Ok, just tried a complete reinstall of eteweb:
```
$ git clone https://github.com/etesync/etesync-web.git
$ cd etesync-web
$ npm install
$ npm run build
$ npm install --no-save serve
Launch server: $ ./node_modules/.bin/serve -s build -l 9001
```

But it sadly is still not working... gettin still:
`undefined is not iterable (cannot read property Symbol(Symbol.iterator))`

**Comment by tasn** [comment]
I think that's the problem. Try using `yarn`. We use `yarn` internally and all the packages are pinned using that.

**Comment by SeanPedersen** [comment]
Hey @tasn  yarn did it!
```
$ git clone https://github.com/etesync/etesync-web.git
$ cd etesync-web
$ yarn install
$ yarn run build
$ yarn add serve
Launch server: $ ./node_modules/.bin/serve -s build -l 9001
```

But the new awesome feature is still not available... See here: https://i.imgur.com/H6rXk4z.png

**Comment by tasn** [comment]
I'm not sure what I'm meant to be seeing, but the feature works like this:
If there's no date set and you set the start date, set end date to start + 30mins. We haven't implemented auto-changing of the end date when you move the start date (and this wasn't asked).
