### ISSUE TITLE
Adress Book - failed parsing item

### ISSUE THREAD

**Issue by mpern** [etesync/etesync-web#206]
Hi all!

I've imported all contacts from Android, but one of them can't be parsed.

It throws an error in the web interface and also breaks the `etesync-dav` bridge. (etesync/etesync-dav#205)

Error Message:

```
invalid line (no token ";" or ":") "1234 Foo/Bar\, Anonymized"
```

(Due to privacy concerns, I won't post the faulty vcard content here)

A simple "Delete" button for the faulty item would be enough to fix this.

**Comment by tasn** [comment]
You can delete it on Android, can't you?

**Comment by mpern** [comment]
You're right!

I was able to edit the contact on Android and fix the issue.
