### ISSUE TITLE
Issue with syncing contacts from any device after trying to sync using Thunderbird

### ISSUE THREAD

**Issue by luvsheth** [etesync/etesync-web#211]
Hi there,

I have succesfully synced across devices using Thunderbird but today I encountered an issue that seems to have broken something. I pressed "Sync Now"

![image](https://user-images.githubusercontent.com/47491349/116987710-f7dd9a80-ad01-11eb-961c-d0c077453e66.png)

And after doing that a few times, things wouldn't sync anymore. I tried to restart my computers and that didn't seem to help. I tried to remove the account from thunderbird and re-add but I now get a HTTP:500 error from the service. The event log is as follows:

```

URL:
https://localhost:37358/**[[MYEMAILID]]**/ (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:prop><cal:calendar-home-set /><d:group-membership /></d:prop></d:propfind>

Response:
A server error occurred.  Please contact the administrator.


```

```

URL:
https://localhost:37358/**[[MYEMAILID]]**/ (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:prop><cal:calendar-home-set /><d:group-membership /></d:prop></d:propfind>

Response:
A server error occurred.  Please contact the administrator.

```

Then I tried to use the migration to ETESync2.0 tool in case that fixed whatever was broken and got this error:
![image](https://user-images.githubusercontent.com/47491349/116987942-48ed8e80-ad02-11eb-90c0-dd870b822b81.png)

Do you know how I might be able to fix this? Please let me know if there's any other info I can provide that might be helpful, tried to include everything I could think of.

Thank you!

**Comment by luvsheth** [comment]
Ok I deleted one of the contact groups that seemed to be the problem group (recently created etc) and stuff seems to be fixed. I could migrate to ETESync2.0 and my thunderbird syncs again.

Thank you.

**Comment by tasn** [comment]
Glad to hear you figured it out. :)
