### ISSUE TITLE
Web App creates events in only one Calendar

### ISSUE THREAD

**Issue by face0b1101** [etesync/etesync-web#22]
I have just tried using the Web App to modify calendar entries.

Although it correctly displays my six calendars, and I can edit existing entries with no problems, I can only create new events on one of the calendars. All the calendars can be selected in the drop down menu, however it always selects and reverts to the same calendar each time. This calendar is neither the first or last calendar I created, and it happens to be a shared calendar if that makes a difference.

Am I doing something wrong?

**Comment by tasn** [comment]
Oops, this obviously shouldn't happen. I'll test and fix it asap.

**Comment by tasn** [comment]
I can confirm this. It's a result of the recent move to the new ui library. Thanks for reporting, will fix it now.

**Comment by face0b1101** [comment]
I can confirm that this now appears to be working.
Thanks for sorting it out so quickly @tasn

**Comment by tasn** [comment]
Yay. :)

My pleasure.
