### ISSUE TITLE
Unable to Create New Account

### ISSUE THREAD

**Issue by QuezXLV** [etesync/etesync-web#236]
I tried to create an account using Firefox (95.0.1) on my Ubuntu (20.04.3) desktop. After entering my information and clicking the “SIGN UP” buttonon the Signup page, the next screen I see says “Deriving encryption data…” with a spinning wheel and it hangs there. I let that sit for a while, but nothing happened and the screen persisted. I then tried to log in on a separate tab in Firefox as well as on the iOS app; however, I then get a message that the user was not found. 

Can this be resolved? Thank you.

**Comment by tasn** [comment]
Could you please try on a different browser/with your add-ons disabled? I suspect that maybe something is blocking the key derivation and making it fallback on a much slower backup implementation.

**Comment by QuezXLV** [comment]
I tried signing up on Safari on iOS and it worked. Many thanks!

**Comment by tasn** [comment]
Sorry for the trouble there.

**Comment by QuezXLV** [comment]
No worries, but I do have another quick question in the meantime ...

Is there no birthday field option available for contact entries, or am I just not seeing it?
