### ISSUE TITLE
Invalid token error

### ISSUE THREAD

**Issue by clnhlzmn** [etesync/etesync-web#245]
On both Firefox 101.0.1 and Edge 102.0.1245.44 I am getting an invalid token error and am unable to login:
![image](https://user-images.githubusercontent.com/20326304/174462635-2f5d1fc1-277c-4622-890e-dc33e35b9dcd.png)

**Comment by clnhlzmn** [comment]
Ok.. Kind of annoying, but I cleared site data for etesync.com (which was not obvious to me because there are apparently no cookies stored but there is "site data"?) and I was able to login after that. I wonder if there is a way to make that solution more obvious or automatic?

**Comment by tasn** [comment]
It should be automatic. It should clear that on this kind of error.

Please let me know if it happens again. I'm closing this in the meantime.
