### ISSUE TITLE
Generate releases

### ISSUE THREAD

**Issue by julianfairfax** [etesync/etesync-web#248]
It would be nice if you could generate GitHub releases for changes so that we know there have been some. This may be on me but I build a version of this package for Arch Linux that is up to date, but since it gets the version number from the releases: https://gitlab.com/julianfairfax/package-repo/-/blob/master/etesync-web/build_arch.sh, Arch won't update it since the releases are never updated.

**Comment by julianfairfax** [comment]
> We can generate new releases, but PKGBUILD has great support for using git tags, as well as getting a sequential count for releases:
> 
> ```
> echo $(printf "%06d" $(git rev-list --count HEAD))   
> ```
> 
> Though let me know if you're facing issues and we can potentially make a new release.

What exactly is this command doing? It doesn't seem that this repo has any tags?

**Comment by tasn** [comment]
This just gives each commit a sequential monotonically increasing ID

**Comment by julianfairfax** [comment]
This seems to have worked
