### ISSUE TITLE
Invalid token and broken synchronization

### ISSUE THREAD

**Issue by shogel0** [etesync/etesync-web#249]
Hi. I use my phone with etesync app installed. Since yesterday I am getting a notification "contacts synchronization failed".  So I went to the web page to see what is going on. i noticed I don't have many events made in my phone. In the activity report last event are from may! I also have an error icon "INVALID TOKEN" . After deleting the account in etesync app and creating it again it seems to work now, but on the page i still have this invalid token. Help?

**Comment by tasn** [comment]
We fixed the underlying issue a few months ago, but I guess you still have a cached stale token. You can try going to your browsers' manage data and delete the data for the etesync app. That will fix it.
Are you also able to "logout", that should do it too.

**Comment by shogel0** [comment]
Delete data? Will it delete all to events and contacts?
