### ISSUE TITLE
On web app, cannot log in b/c it is requesting my encryption pw before I have created it

### ISSUE THREAD

**Issue by smallfry37** [etesync/etesync-web#26]
I am using firefox browser in incognito mode.  I have created an account.  When I go to log in it is requiring my encryption password, but I haven't  been prompted to (or found a place I can) create this encryption pw yet, so I cannot use the service.

EDIT:  filling out the encryption field SET my encryption password, but that was not clear from the interface.  Not a but but a UI issue.

**Comment by tasn** [comment]
The UI is not perfect in this regard, but the first encryption password you
put in will be your encryption password. So essentially read it as "please
set your encryption password".

I should fix this, I know.
