### ISSUE TITLE
Bad signature

### ISSUE THREAD

**Issue by panda2134** [etesync/etesync-web#269]
The plugin "Signed pages" reports a bad signature for https://pim.etesync.com. Is the frontend hacked?

**Comment by panda2134** [comment]
This issue only persists in Vivaldi, so I guess it's a browser specific issue.

**Comment by rugk** [comment]
You may want to report this to https://github.com/tasn/webext-signed-pages/issues as it likely is an extension issue then (or a combination with browser/browser settings). In any case likely useful to have some debugging information.
