### ISSUE TITLE
On web app, deleting a calendar shows a confirmation asking user to "delete contact"

### ISSUE THREAD

**Issue by m0unds** [etesync/etesync-web#27]
Hey,

When you're logged in to the web app, accessing a synced calendar and want to delete an item from it, instead of asking the user to confirm deletion of a calendar item, it asks for confirmation to delete a "contact".

Super minor issue, but just noticed it while I was trialling the hosted service.

Thanks!

![screenshot](https://i.imgur.com/Twl9Ftg.png)

**Comment by tasn** [comment]
Fixed, thanks for reporting!
