### ISSUE TITLE
Network request failed on Web application

### ISSUE THREAD

**Issue by fdroiduser** [etesync/etesync-web#271]
Hi,
Since 24 hours or so, I keep getting **Network request failed** after entering my credential on https://pim.etesync.com/login
Note that it first goes through ("Deriving encryption data…"), and then goes back to the login page with the error "Network request failed"

I wonder whether this is related to my account, or to the Web application itself, or to a server problem. My Evolution calendar does not synchronize any longer with my Android calendar since yesterday either, and Android Etesync aborts with an error:
`java.net.SocketTimeoutException: failed to connect to api.etebase/ (IP) (port 443) from (IP) after 15000ms`

**Comment by tasn** [comment]
Yup fixed, sorry about that!
