### ISSUE TITLE
Cannot read property 'journalUid' of undefined

### ISSUE THREAD

**Issue by wireddude** [etesync/etesync-web#3]
1. verify your contact sync is on both web and mobile
2. delete contact on mobile device
3. go to that contact on web - it shows up, but then I refreshed manually on webui and got the error below.

![screen shot 2018-01-02 at 10 18 11 am](https://user-images.githubusercontent.com/5432629/34494718-9dc1e496-efa6-11e7-8c39-20a8cdb01f4d.png)

**Comment by tasn** [comment]
Does this happen when trying to view a deleted contact?

If so, yeah, I'm aware of that, I need to fix these error pages to be 404s. The whole "page not found" concept is not yet implemented in the web ui.

Thanks for reporting.

**Comment by wireddude** [comment]
Yes, basically when you try to view a deleted contact you get this error. A more graceful 404 or error page would be better.

**Comment by tasn** [comment]
OK, what I thought, thanks.

Will try to get to this soon.
