### ISSUE TITLE
0.4.0 no release notes

### ISSUE THREAD

**Issue by rugk** [etesync/etesync-web#33]
The [v0.4.0](https://github.com/etesync/etesync-web/releases/tag/v0.4.0) is only tagged on GitHub, but has no release information attached to it.

**Comment by tasn** [comment]
See https://github.com/etesync/etesync-web/releases/tag/v0.3.0

It's still in such an early stage and enough is changing to make this changelog a bit to handle... I think things are stabilising so it'll get better soon.

**Comment by rugk** [comment]
> In the future these release tags will include proper changelog
information.

v0.4.0 is in the future of v0.3.0, but if this still stands, then okay.

**Comment by tasn** [comment]
Yeah, sorry for the brevity. I meant it still stands. It'll stay this way until you see an up to date changelog in the repo...
