### ISSUE TITLE
Address Book should use case-insensitive sorting

### ISSUE THREAD

**Issue by dere** [etesync/etesync-web#34]
If you create a contact named `Alice` and another named `alice`, you would expect they would be displayed near each other in the Address Book on the Etesync web app, but `Alice` will be near the top of the list and `alice` will be at the bottom. This is because the sorting method used by the Address Book component unintentionally sorts capitals before lower-case letters. This is inconsistent with traditional expectations that `alice` and `Alice` would be near each other on the list (see: the Contacts app on Android, for example).

**Comment by tasn** [comment]
Oops, thank for reporting. :)
