### ISSUE TITLE
Viewing a new journal results in "Journal not found"

### ISSUE THREAD

**Issue by dere** [etesync/etesync-web#35]
Suppose you create a new journal (presumably of any type, but I've only tested Address Book and Calendar), you will find it is impossible to add entries to it, because clicking on the journal from the Journals page will result in "Journal not found!" error, instead of an empty calendar or contacts list, for example. Surprisingly, the Default journal never does this: even though I have an empty Default journal of type Calendar, clicking on it shows me the empty calendar as expected. Also, the mobile app does not have this problem: clicking on any of these new journals will show a journal with zero entries.

**Comment by dere** [comment]
If you create an entry in the journal using a different calendar app for example and sync, now that there is a entry in the journal you are able to view your new calendar. If you delete that entry using the web app, after hitting refresh you won't be able to view the journal anymore since it has 0 entries again.

**Comment by dere** [comment]
Now I'm not able to replicate this behavior so I don't know.

**Comment by dere** [comment]
You have to create the new journal *in the web app*. If you create it using the mobile app, you're able to view it just fine in the web app, even if it has zero entries.

Additionally there is another weird interaction:

1. Create a new calendar journal *using the web app*
2. Sync the mobile app. The new journal will appear
3. Create a new event in that journal using some Calendar app. You will now be able to view the journal using the web app, but it will be empty until it is synced.
4. Press the sync button in the mobile app, and refresh the web app. The new event will appear.
5. Delete the event *using the web app*
6. Either sync the mobile app or refresh the web app. You will find in both cases your entire journal is gone without a trace.

**Comment by tasn** [comment]
Oops, this code is very new, as you can see, it's still not 100% correct. For example there's the matter of #36.

**Comment by dere** [comment]
The goal of etesync is to provide a centralized E2EE syncing service as a data source for other apps (Thunderbird etc) -- an amazing, Google-quality webapp isn't necessary to meet that goal, otherwise you'll be spending all your time rewriting Thunderbird Calendar. But, if I see an easy-to-fix bug like this one, I'll report it because why not

**Comment by tasn** [comment]
EteSync started with the goal you stated, but the web client grew out of user demand, and I now consider it an important part of the suite. I'd love to gave a Google quality web app. :) It's not the highest priority, but it's definitely on the roadmap. :)

Please keep on reporting any issues you see!
