### ISSUE TITLE
[FEATURE] Open calendar week+day view at reasonable time

### ISSUE THREAD

**Issue by Nuntius0** [etesync/etesync-web#40]
**Currently**
When you open the week or day view in the calendar, its scroll position is at the top.
This requires you to scroll down in 99% of cases.

**Better way**
Set the scroll position such that 6am is at the top. Then most of the day is already in view.

6am seems like a good choice to me, others are possible too.
Some people may have things as early as 6, and if not then you have some whitespace of one or two hours before your first entry, which looks good as well - otherwise it may look too compressed.

Just NOT fall in the classic trap for open source projects and make it a setting, a good default will be better in the longterm :)

**Why**
In reality you don't have many appointments between 0am and 6am.

**Comment by tasn** [comment]
I'd love that, though unfortunately it's not supported by react-big-calendar, the library we use for the calendar. :(

Maybe open a ticket there?

**Comment by Nuntius0** [comment]
Which library is that? [This](https://github.com/intljusticemission/react-big-calendar) one?
If so, they seem to have that: http://intljusticemission.github.io/react-big-calendar/examples/index.html#prop-scrollToTime (and they actually do it on their demo site, and scroll to 6am as well :innocent: )

**Comment by tasn** [comment]
I looked at this property before and it didn't look right because it accepts a date, not a time... Though apparently it is the correct one, the API is just weird!

Fixed, will push now. Thanks!
