### ISSUE TITLE
Mobile Not Syncing

### ISSUE THREAD

**Issue by derpyderpydo** [etesync/etesync-web#42]
I use Etesync in three ways.

On the desktop, I use it in Thunderbird with a local docker image.

If, for some reason, Thunderbird is being slow - I may fall back to using the web client at  https://client.etesync.com/pim

And of course, on my android device, of which I have 1.4.0 installed.

I can add items to my calendar on the Web and have them show up in Thunderbird.  I can add items in Thunderbird and have them show up on the web.

Neither are currently showing up on my phone.  I have manually synced.  I have force-quit the application and re-opened it and manually synced again.  I'm not getting journal change notifications and my local calendar - which seems to pull all my calendars from Etesync from a later date ( i don't know when the last successful sync was).

**Comment by tasn** [comment]
Hey,

Sorry to hear. This is better suited as a report to support@etesync.com than an issue here as it works for me (just verified), and I assume it works for others too...

Could you please enable logging to file and send that email the file (make sure it doesn't contain any sensitive information). Additionally also send the debug info from Settings -> Debug Info if possible?

I'm closing this ticket, but please email me with the above and we'll figure it out.
