### ISSUE TITLE
Blank homepage

### ISSUE THREAD

**Issue by romjean** [etesync/etesync-web#45]
Hi,
Just installed the web-app to a subdir of my domain: www.xxxxxxxxx.xx/sync/
Added the "homepage": "/sync" directive in the package.json
I have a blank white page when I access to the homepage https://www.xxxxxxx.xx/sync/
Do I need to rebuild after having added the subdir directive or should it work without ?
How do the web-app know to connect to etesync local server ?
Thanks a lot for your help
RomJean

**Comment by tasn** [comment]
You need to rebuild. Let me know how it goes.

**Comment by romjean** [comment]
Thanks.
Now I can access to the website. However, it's empty :-(
<img width="1440" alt="empty" src="https://user-images.githubusercontent.com/15798122/59144919-079cb900-89dd-11e9-8f7b-0b5f9d7dd655.png">

**Comment by romjean** [comment]
Don't know if it's an issue, but I set up the app to serve a sub-directory of my virtualhost with `"homepage": "/sync"`. However, the actual served directory is located under `WEB_ROOT_DIR/etesync/build/` and I've created an Alias in my Apache's configuration to serve it properly.

**Comment by romjean** [comment]
Hi,
In my apache's log, I can see
`[Tue Jun 11 13:04:40.577313 2019] [proxy:error] [pid 9603] (111)Connection refused: AH00957: HTTP: attempt to connect to 127.0.0.1:8000 (localhost) failed
[Tue Jun 11 13:04:40.577555 2019] [proxy_http:error] [pid 9603] [client my.IP.address:60131] AH01114: HTTP: failed to make connection to backend: localhost`
Could it be the problem ?

**Comment by tasn** [comment]
It's hard to know without knowing your exact setup.

I don't know why apache would see your failed connections to the etesync server in the way that it did. It looks like you have a few things going on there.


1. EteSync server: hosted on localhost or a server?
2. EteSync client (apache): loaclhost or a server?
3. Does your self-hosted etesync server otherwise work (e.g. with the Android client)?
4. Do you have https set up for the etesync server?
5. What is the server you put in the "custom server" field?

Looking forward to getting the details, but it would be better if we could isolate things by testing them separately.

**Comment by romjean** [comment]
> It's hard to know without knowing your exact setup.
> 
> I don't know why apache would see your failed connections to the etesync server in the way that it did. It looks like you have a few things going on there.
> 
> 1. EteSync server: hosted on localhost or a server?

localhost port 8000

> 2. EteSync client (apache): loaclhost or a server?

localhost

> 3. Does your self-hosted etesync server otherwise work (e.g. with the Android client)?

Yes, with Android app it works perfectly, I can see the logs updating while I'm synchronizing

> 4. Do you have https set up for the etesync server?

Yes

> 5. What is the server you put in the "custom server" field?

Where do I find this setting ?

> Looking forward to getting the details, but it would be better if we could isolate things by testing them separately.

**Comment by romjean** [comment]
I finally get to make it work.
I basically created a new subdomain client.mydomain.fr and didn't add any "homepage": "/xxx" in the package.json file.
It works !
Thanks a lot for your help
RomJean

**Comment by tasn** [comment]
Glad to hear it works!

What do you mean by complete path? I'm not sure about subdomain. I've helped people to set it up before but it's really just setting up according to whatever create-react-app dictates. (yeah, I know it's not obvious and documentation can be better).

Regarding the custom server URL you used: this makes the error you got from Apache seem very odd. Anyhow, as long as it's working. :)

**Comment by romjean** [comment]
> What do you mean by complete path?

Instead of `"/sub-directory"`, put `https://www.mydomain.fr/sub-directory"`
I didn't tried but If think this caused m'y web-app not to work.

Anyway great thanks for your help

**Comment by tasn** [comment]
You seem to be correct: https://facebook.github.io/create-react-app/docs/deployment

**Comment by romjean** [comment]
Yep, that's exactly where I picked it up
