### ISSUE TITLE
Issues with viewing events/contacts/tasks with the same uid across journals

### ISSUE THREAD

**Issue by tasn** [etesync/etesync-web#46]
If you have e.g. a contact with the same uid in two different journals only one of them can be viewed and worked on (impossible to know which). The reason for that is that the URL used to access events is: `/pim/events/fe65daf1-9049-41cb-9fc2-99993779f235` which doesn't include the jorunal uid in it.

It shouldn't really happen under normal use, but it can happen.

**Comment by ramzan** [comment]
Looks like this was fixed at some point.

**Comment by tasn** [comment]
Correct it's indeed fixed, thanks!
