### ISSUE TITLE
r[0] is undefined on Address Book tab

### ISSUE THREAD

**Issue by michaelvandeweerd** [etesync/etesync-web#49]
Clicking the "Address Book" tab on the main page of the webclient gives me the following error:

![image](https://user-images.githubusercontent.com/4655516/64081037-d7bf3200-ccfb-11e9-853a-e4c6615850f7.png)

As a result I cannot view my contacts on the webclient, although they are visible in Thunderbird and on my phone.

**Comment by tasn** [comment]
Thanks for the report! I'll try to figure this out. Annoying that, as you can see, the debug information is not great on the web client in production mode. :)

**Comment by tasn** [comment]
I'm pretty sure it's fixed, please reopen if it isn't. The problem was that you had a contact (multiple?) with no name.

**Comment by michaelvandeweerd** [comment]
Works perfectly, thank you!

**Comment by tasn** [comment]
Yay, thanks for letting me know!
