### ISSUE TITLE
"Event should be defined" when viewing recurring event

### ISSUE THREAD

**Issue by cniesen** [etesync/etesync-web#56]
After a recurring event is created (i.e. via android stock calendar app) the detail of the first event is displayed correctly when clicking on the event.  For the other events the following error is created:
```
render
../etesync-web/src/components/Event.tsx:16
finishClassComponent
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:14979
updateClassComponent
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:14934
beginWork
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:15840
performUnitOfWork
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:19745
workLoop
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:19786
callCallback
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:147
invokeGuardedCallbackDev
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:196
invokeGuardedCallback
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:250
replayUnitOfWork
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:18976
renderRoot
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:19899
performWorkOnRoot
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:20811
performWork
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:20721
performSyncWork
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:20695
interactiveUpdates$1
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:20983
interactiveUpdates
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:2267
dispatchInteractiveEvent
../etesync-web/node_modules/react-dom/cjs/react-dom.development.js:5081
```
The cause is that the subsequent recurring react events components don't have the props.item set.
```
  public render() {
    if (this.props.item === undefined) {
      throw Error('Event should be defined!');
    }
```
With my limited knowledge it looks like the issue is in PimMain.tsx at this code snipped
```
  public eventClicked(event: ICAL.Event) {
    // FIXME:Hack
    const itemUid = `${(event as any).journalUid}|${event.uid}`;
```
where `${(event as any).journalUid}` returns "undefined".

This traces back to the render method of Calendar.tsx where the event is cloned. This clone does not replicate the `journalUid` property of the event.

Thinking of being smart I added the following statement after the clone
```
ev.journalUid = event.journalUid
```
which caused the error message: "Property 'journalUid' does not exist on type 'EventType'."
I think that explains also why the clone dropped the property.

![etesync](https://user-images.githubusercontent.com/3842973/66799988-feff4680-eed8-11e9-916d-4344d4222942.jpg)

**Comment by cniesen** [comment]
Related to some comments of #50

**Comment by tasn** [comment]
You actually did everything correctly, the only thing you did wrong is that you should have used:
`(ev as any).journalUid = (event as any).journalUid;`
instead of
`ev.journalUid = event.journalUid;`

Does it fix it?

I know it's very hacky. The journalUid thing is a workaround that should be better handled.

**Comment by cniesen** [comment]
Yep, that fixes it.   Updates and deletes work as well with the caveats that the whole series will be updated/deleted.

**Comment by tasn** [comment]
Yeah, that's a known "issue". It's just not implemented yet, that's why there's the big fat warning about it. :)
