### ISSUE TITLE
Creating a single day "all day event" spans 2 days in the calendar month view

### ISSUE THREAD

**Issue by wireddude** [etesync/etesync-web#6]
I made an all day event for 1/21/18, but the calendar view shows it spanning 1/21/18 - 1/22/18. Any idea why? Should just be 1 day.

![screen shot 2018-01-15 at 2 41 17 pm](https://user-images.githubusercontent.com/5432629/34965048-28b4f9e4-fa06-11e7-9b9b-3d289f266d02.png)
![screen shot 2018-01-15 at 2 41 23 pm](https://user-images.githubusercontent.com/5432629/34965125-9f9ff23e-fa06-11e7-969f-7b5c07e13da9.png)

![screen shot 2018-01-15 at 2 41 33 pm](https://user-images.githubusercontent.com/5432629/34965082-5901a278-fa06-11e7-93a2-56fe1b64b2d9.png)

**Comment by tasn** [comment]
Thanks for reporting.

This is a known issue. It's a bug with the underlying calendar component we use. I reported it to them here: https://github.com/intljusticemission/react-big-calendar/issues/680

I hope they fix it soon, but if they don't I may look into changing to a different library.
