### ISSUE TITLE
Integrity Error

### ISSUE THREAD

**Issue by rafaelmr2** [etesync/etesync-web#66]
> Integrity Error
> 
> Please log out from the menu, refresh the page and try again, and if the problem persists, contact support.
> 
> Bad HMAC. 8a7db796187ce096c05a9573eafd69777734bb5672d86f9b61ac07fe4f472fe9 != 5a0f909f3064976cb45c5e5387f777c29314ad25b7f1b0d83fa89b85cee81e28

When try to login, i get the error above.

I'm testing my own etesync server instance, I try access via client.etesync.com. With Android app I don't have problem.

Thanks.

**Comment by tasn** [comment]
Are you using OpenTasks on Android?
Are you using your own self-hosted etesync-web, or the client hosted on client.etesync.com?
Have you changed your encryption password recently?

This kind of error almost always means a wrong encryption password, or in the case of self-hosting it could be you've been doing something funny on the server. Could you please try accessing the web client in incognito mode?

Thanks,
Tom

**Comment by rafaelmr2** [comment]
Yes, I'm using Tasks (from F-Droid). I'm using etesync-web from client.etesync.com. I tried in incognito mode and others browsers. No, I didn't change password. It's login with pass and key normally in Android.

Thanks

**Comment by rafaelmr2** [comment]
Hi,

I removed some calendars, and it's working now.

Thanks.

**Comment by tasn** [comment]
What version of Tasks?
Did you have to remove calendars or task lists?
This is quite odd. :|

**Comment by rafaelmr2** [comment]
I use version 1.2.3, from F-Droid. I removed calendars.

**Comment by tasn** [comment]
No idea what it could be then. I'd advise to make sure your clients and server are always up to date.
I just pushed a commit to Android that should extra protect against this kind of issues happening, though I don't think it would really make a difference as these shouldn't happen and haven't been happening for at least a year.

Anyhow, I'm closing this unless we have any more actionable information. It's not an issue with the web client anyway, but rather most likely with the Android client as from your report it seems to be the one who created these entries.
