### ISSUE TITLE
Feature request: clicking on a time slot to add a calendar entry

### ISSUE THREAD

**Issue by davidwisniewski** [etesync/etesync-web#8]
It would be great to have the option to click on a specific time slot in the calendar view to add an entry at that point in time. 
Right now, when hit the Add button, I need to select both day (and time) even if I have the one-day view open.

**Comment by tasn** [comment]
Thanks, I agree, it's extremely annoying.
I need to check if the calendar widget used (react-big-calendar) even supports it. If not, I'll open a feature request, if yes, I'll just implement it.

**Comment by davidwisniewski** [comment]
Awesome, works like a charm.
