### ISSUE TITLE
Contact ical component uses 'rev' instead of 'last-modified'

### ISSUE THREAD

**Issue by AbleLincoln** [etesync/etesync-web#83]
https://github.com/etesync/etesync-web/blob/680f9698a73c86d885f795367516ecdd0248b7c6/src/components/ContactEdit.tsx#L281

It looks like you are using this `rev` property to track when Contact ical components were last modified. According to the [spec](https://tools.ietf.org/html/rfc5545#section-3.8.7.3), the proper name is `LAST-MODIFIED`. This property name is being correctly used in other parts of the library (for Calendar Events and Tasks). 

I'm curious, is there a reason we have `rev` here instead of `last-modified`?

**Comment by tasn** [comment]
The code you linked to is for contacts and the RFC you linked to is for calendars. REV is the property name for vCard and last-modified is the property name for calendars. That's why they are different.
Relevant part of the spec: https://tools.ietf.org/html/rfc6350#section-6.7.4
