### ISSUE TITLE
Change text color for lightly colored journals

### ISSUE THREAD

**Issue by betsythefc** [etesync/etesync-web#85]
<img width="1160" alt="Screen Shot 2020-03-11 at 9 34 48 AM" src="https://user-images.githubusercontent.com/15450365/76440978-ec037c00-637b-11ea-8373-f6dddd8bb407.png">
I have a task list that uses a light color, but the web client doesn't make the text dark, so it's impossible to read.

**Comment by tasn** [comment]
Could you force refresh the page? We already changed how tasks are done (unrelated to this ticket) so they go directly to the edit page when clicked. This means you won't even get to this issue.

**Comment by betsythefc** [comment]
I force reloaded, and it works, thanks!

**Comment by tasn** [comment]
No problem. I'm going to fix a related issue with calendar events though, pushing now. So thanks again for reporting. :)
